
REM COMPILE SOURCE MODULES WHICH ARE USED IN THE CALL MONITOR PROGRAM
REM
CD CALLMON
msc %1 /Gs MONIIO;
msc %1 /Gs CALLMON;
msc %1 /Gs FMON;
msc %1 /Gs MONDATA;
masm MONINT;
masm ASMUTL;
masm MOVPARAM;
REM
REM COMPILE SOURCE MODULES WHICH ARE USED IN THE MONITOR
REM
CD ..\MON
MSC %1 /Gs DATA.C;
MSC %1 /Gs DUMP.C;
COPY ..\HDR\COMMASM.H
MASM IOC2;
DEL COMMASM.H
MSC %1 /Gs IOU2.C;
MSC  %1 /Gs MON.C;
MSC  %1 /Gs MONCHMOD.C;
MSC  %1 /Gs MONCLINK.C;
MSC  %1 /Gs MONDATA.C;
MSC  %1 /Gs MONERROR.C;
MSC  %1 /Gs MONPLINK.C;
MSC  %1 /Gs MONVPKT.C;
MSC  %1 /Gs PKTMSG.C;
REM
REM COMPILE SOURCE MODULES WHICH ARE USED IN THE TEST PROGRAM
REM
CD ..\TST
MSC %1 /Gs AI.C;
MSC %1 /Gs AIERROR.C;
MSC %1 /Gs AIFUNC.C;
MSC %1 /Gs CALL.C;
MSC %1 /Gs CHNL.C;
MSC %1 /Gs COUT.C;
MSC %1 /Gs GETREQ.C;
MSC %1 /Gs GETTEXT.C;
MSC %1 /Gs GETWORD.C;
MSC %1 /Gs HELP.C;
MSC %1 /Gs STATUS.C;
MASM VEC;
MASM INTFUNC;
REM
REM COMPILE SOURCE MODULES WHICH ARE USED BY MAN
REM
CD ..\MAN
MSC /Gs MAN.C;
cd ..


