
REM THIS SCRIPTS COMPILES ALL OF THE SOURCE MODULES WHICH ARE NEEDED FOR
REM THE XPC DRIVER. LIBRARIES WHICH ARE NEEDED ARE CREATED.
REM THIS SCRIPT ASSUMES THAT  THE STARTING DIRECTORY IS WHERE THE
REM XPCMAIN DRIVER CODE IS LOCATED.
REM
REM IF DEBUGGING IS TO BE TURNED ON START SCRIPT WITH THE /DDEBUG OPTION:
REM CMPXPC /DDEBUG
REM
REM 
MSC %1 /Gs DATA.C;
MSC %1 /Gs XPCMAIN.C;
del *.inc
REM 
REM COMPILE PAD PACKET SUBROUTINES AND CREATE THE PKT LIBRARY
REM
CD PKT
MSC  %1 /Gs BALL.C;
MSC  %1 /Gs ECHO.C;
MSC  %1 /Gs GETBUF.C;
MSC  %1 /Gs LINKXMIT.C;
MSC  %1 /Gs MCIWRITE.C;
MSC  %1 /Gs OTHWRITE.C;
MSC  %1 /Gs PADPRM.C;
MSC  %1 /Gs PERROR.C;
MSC  %1 /Gs PKTBREAK.C;
MSC  %1 /Gs PKTCHNL.C;
MSC  %1 /Gs PKTFLUSH.C;
MSC  %1 /Gs PKTREAD.C;
MSC  %1 /Gs PKTSTAT.C;
MSC  %1 /Gs PKTWRITE.C;
MSC  %1 /Gs RDQUEUE.C;
MSC  %1 /Gs SENDCTRL.C;
MSC  %1 /Gs SSNACP.C;
MSC  %1 /Gs SSNCLR.C;
MSC  %1 /Gs SSNDATA.C;
MSC  %1 /Gs SSNREQ.C;
MSC  %1 /Gs TIMEOUT.C;
MSC  %1 /Gs TYMWRITE.C;
MSC  %1 /Gs WRTSUBS.C;
DEL PKT.LIB
LIB @PKTLIB
REM 
REM COMPILE MODULES FOR THE APPLICATION LIBRARY AND CREATE THE APPL LIBRARY.
REM 
CD ..\APPL
MSC  %1 /Gs APPINIT.C;
MASM APPINT.ASM;
MSC  %1 /Gs CHFLUSH.C;
MSC  %1 /Gs CHFUNC.C;
MSC  %1 /Gs CHSTAT.C;
MSC  %1 /Gs CRDATA.C;
MSC  %1 /Gs CWDATA.C;
MSC  %1 /Gs DEVICE.C;
MSC  %1 /Gs EVENT.C;
MSC  %1 /Gs JMPCHAR.C;
MSC  %1 /Gs JMPPKT.C;
MSC  %1 /Gs JMPRS.C;
MSC  %1 /Gs LINECTRL.C;
MSC  %1 /Gs LINKSTAT.C;
MSC  %1 /Gs PKTFUNC.C;
MSC  %1 /Gs PORT.C;
MSC  %1 /Gs XPCAPP.C;
DEL APPL.LIB
LIB @APPLIB
REM 
REM COMPILE MODULES FOR LINK LIBRARY AND CREATE THE LINK LIBRARY.
REM
CD ..\LINK
MSC %1 /Gs BLDCPKT.C;
MSC %1 /Gs CLINK.C;
MSC %1 /Gs DOLINK.C;
MSC %1 /Gs FLOWCTRL.C;
MSC %1 /Gs LINKINIT.C;
MSC %1 /Gs LINKINP.C;
MSC %1 /Gs LINKOUT.C;
MSC %1 /Gs LINKTIME.C;
MSC %1 /Gs PLINK.C;
MSC %1 /Gs RESET.C;
MSC %1 /Gs RESTART.C;
MSC %1 /Gs RSTCHNL.C;
MSC %1 /Gs SEQNUM.C;
MASM TIMEINT.ASM;
MSC %1 /Gs TIMUTIL.C;
MSC %1 /Gs VALPKT.C;
MSC %1 /Gs CHGSTATE.C;
DEL LINK.LIB
LIB @LNKLIB
REM
REM COMPILE MODULES FOR IOCOMM LIBRARY AND UPDATE THE IOCOMM LIBRARY.
REM
CD ..\IOCOMM
COPY ..\HDR\COMMASM.H
MASM IOCOMM.ASM;
DEL COMMASM.H
MSC %1 /Gs IOUTIL.C;
DEL IOCOMM.LIB
LIB @IOCLIB
REM
REM COMPILE MODULES FOR UTIL LIBRARY AND UPDATE THE UTIL LIBRARY
REM
CD ..\UTIL
MASM ASMUTL.ASM;
MSC %1 /Gs BUFLET.C;
MSC %1 /Gs DOSUTL.C;
MSC %1 /Gs GETCRC.C;
MSC %1 /Gs INITPAD.C;
MSC %1 /Gs MISC.C;
MASM MOVPARAM.ASM;
MSC %1 /Gs QUEFLUSH.C;
MSC %1 /Gs QUEUE.C;
MSC %1 /Gs RDDATA.C;
MSC %1 /Gs TIMER.C;
MSC %1 /Gs OKFREE.C;
MSC %1 /Gs ADJLEN.C;
MASM UPDATE.ASM;
DEL UTIL.LIB
LIB @UTLLIB
cd ..

